name: Java Maven Run Test Suites

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Kill existing Edge processes
        run: pkill -f "msedge"

      - name: Run Test Suites with Maven
        run: mvn test --file pom.xml
