name: Java Maven Run Test Suites

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test Suites with Maven
      run: mvn -B test --file pom.xml -Dsurefire.suiteXmlFiles=testSuites/TestSuite1.xml,testSuites/TestSuite2.xml,testSuites/TestSuite3.xml,testSuites/TestSuite4.xml
