name: SauceDemo Automation workflow

on:
  pull_request:
    branches:
      - main  # You can adjust the branch as needed
  push:
  workflow_dispatch:

jobs:
  E2E:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Clean
      run: mvn clean test
